spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/pet_sitting}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173} 